const brandName = 'মুগল দরবার';
const brandNameLatin = 'Mughal Darbar';
const brandInitial = 'ম';
const brandDescriptor = 'রেস্টুরেন্ট';
const brandTeam = `${brandName} টিম`;

const primaryPhone = {
	display: '+৮৮০ ১৯১৭-৫০৩৫৮০',
	href: 'tel:+8801917503580',
};

const secondaryPhone = {
	display: '+৮৮০ ১৯৫০-৪৯৬৬৮৩',
	href: 'tel:+8801950496683',
};

const featuredItems = [
	{
		id: 1,
		name: 'চিকেন পিৎজা',
		description: 'রসালো চিকেন, গলানো চিজের বন্যা এবং সিক্রেট সস দিয়ে তৈরি',
		price: '১৫০-২০০',
		image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.1.0&auto=format&fit=crop&w=600&q=80',
		badge: 'বেস্ট সেলার',
	},
	{
		id: 2,
		name: 'চিকেন পাস্তা',
		description: 'ক্রিমি সস, টেন্ডার চিকেন এবং পারফেক্ট সিজনিং',
		price: '১০০',
		image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.1.0&auto=format&fit=crop&w=600&q=80',
		badge: 'জনপ্রিয়',
	},
	{
		id: 3,
		name: 'ফ্রাইড রাইস + ক্রিসপি চিকেন',
		description: 'গরম ভাত, ক্রিসপি চিকেন - এক প্লেটে পূর্ণ তৃপ্তি',
		price: '১৩০',
		image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-4.1.0&auto=format&fit=crop&w=600&q=80',
		badge: 'সেট মেনু',
	},
];

const blogPosts = [
	{
		id: 1,
		title: 'কেন চিজ দেখলে আমাদের ব্রেইন পাগল হয়ে যায়?',
		excerpt: 'চিজের ভেতরে থাকা ক্যাসোমরফিন নামক একটি যৌগ আমাদের মস্তিষ্কে ডোপামিন রিলিজ করে। এই কারণেই গলানো চিজ দেখলে আমরা নিজেদের সামলাতে পারি না। জানুন বিজ্ঞানের পেছনের গল্প...',
		image: 'https://images.unsplash.com/photo-1552539618-7eec9b4d1796?ixlib=rb-4.1.0&auto=format&fit=crop&w=800&q=80',
		date: '১৫ জানুয়ারি, ২০২৬',
		readTime: '৫ মিনিট',
		author: brandTeam,
		category: 'খাবারের বিজ্ঞান',
	},
	{
		id: 2,
		title: 'অফিসের স্ট্রেস কাটানোর সবচেয়ে সহজ উপায়: এক প্লেট গরম পাস্তা!',
		excerpt: 'সারাদিন কাজের চাপে যখন মাথা ঘোরে, তখন এক প্লেট ধোঁয়া ওঠা পাস্তা হতে পারে আপনার সেরা বন্ধু। কার্বোহাইড্রেট কীভাবে মুড ভালো করে, জানুন বিস্তারিত...',
		image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.1.0&auto=format&fit=crop&w=800&q=80',
		date: '১০ জানুয়ারি, ২০২৬',
		readTime: '৪ মিনিট',
		author: brandTeam,
		category: 'লাইফস্টাইল',
	},
	{
		id: 3,
		title: 'মুগদার খাবার সংস্কৃতি: আমাদের গর্ব, আমাদের স্বাদ',
		excerpt: 'মুগদা এলাকায় খাবারের প্রতি মানুষের ভালোবাসা অন্যরকম। এখানকার প্রতিটি পরিবারে আছে নিজস্ব রান্নার ঐতিহ্য। মুগল দরবার সেই ঐতিহ্যকে আধুনিকতার সাথে মিশিয়েছে...',
		image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?ixlib=rb-4.1.0&auto=format&fit=crop&w=800&q=80',
		date: '৫ জানুয়ারি, ২০২৬',
		readTime: '৬ মিনিট',
		author: brandTeam,
		category: 'আমাদের গল্প',
	},
];

const menuItems = [
	{
		id: 1,
		category: 'pizza',
		name: 'চিকেন পিৎজা রেগুলার',
		size: '৭" - ৯"',
		price: '১৫০ - ২০০',
		image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'রসালো চিকেন, মোজারেলা চিজ এবং স্পেশাল সস',
		popular: true,
	},
	{
		id: 2,
		category: 'pizza',
		name: 'সস পিৎজা',
		size: '৭" - ৯"',
		price: '১৫০ - ২০০',
		image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'টম্যাটো সস, হার্ব এবং গলানো চিজ',
		popular: false,
	},
	{
		id: 3,
		category: 'pizza',
		name: 'মাশরুম পিৎজা',
		size: '৭" - ৯"',
		price: '১৫০ - ২০০',
		image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'ফ্রেশ মাশরুম, চিজ এবং ইতালিয়ান হার্ব',
		popular: false,
	},
	{
		id: 4,
		category: 'pizza',
		name: 'ওভারলোড চিকেন পিৎজা',
		size: '৭" - ৯"',
		price: '২০০ - ২৫০',
		image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'এক্সট্রা চিকেন, ডবল চিজ এবং লোডেড টপিংস',
		popular: true,
	},
	{
		id: 5,
		category: 'pasta',
		name: 'এগ নুডলস',
		size: '',
		price: '৭০',
		image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'ডিম দিয়ে তৈরি সুস্বাদু নুডলস',
		popular: false,
	},
	{
		id: 6,
		category: 'pasta',
		name: 'চিকেন নুডলস',
		size: '',
		price: '১০০',
		image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'টেন্ডার চিকেন পিস সহ নুডলস',
		popular: true,
	},
	{
		id: 7,
		category: 'pasta',
		name: 'পাস্তা রেগুলার',
		size: '',
		price: '৭০',
		image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'ক্লাসিক ইতালিয়ান স্টাইল পাস্তা',
		popular: false,
	},
	{
		id: 8,
		category: 'pasta',
		name: 'চিকেন পাস্তা',
		size: '',
		price: '১০০',
		image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'ক্রিমি সস এবং গ্রিলড চিকেন',
		popular: true,
	},
	{
		id: 9,
		category: 'pasta',
		name: 'চিজ পাস্তা',
		size: '',
		price: '১৫০',
		image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'এক্সট্রা চিজি এবং ক্রিমি',
		popular: true,
	},
	{
		id: 10,
		category: 'setmenu',
		name: 'ফ্রাইড রাইস + ক্রিসপি চিকেন',
		size: '',
		price: '১৩০',
		image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'গরম ফ্রাইড রাইস এবং ক্রিসপি ফ্রাইড চিকেন',
		popular: true,
	},
	{
		id: 11,
		category: 'setmenu',
		name: 'ফ্রাইড রাইস + চিকেন কারি',
		size: '',
		price: '১৩০',
		image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'ফ্রাইড রাইস এবং ঝাল চিকেন কারি',
		popular: false,
	},
	{
		id: 12,
		category: 'setmenu',
		name: 'ফ্রাইড রাইস + ক্রিসপি চিকেন + কারি',
		size: '',
		price: '২০০',
		image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.1.0&auto=format&fit=crop&w=500&q=80',
		description: 'কমপ্লিট মিল - ভাত, চিকেন এবং কারি',
		popular: true,
	},
];

export const clientConfig = {
	brand: {
		name: brandName,
		nameLatin: brandNameLatin,
		initial: brandInitial,
		descriptor: brandDescriptor,
		shortTagline: 'মুগদার সেরা ফাস্ট ফুড',
		intro: 'মুগদার বুকে আপনার প্রিয় ফাস্ট ফুড ডেস্টিনেশন। গরম, রসালো এবং মুখরোচক খাবারের নিশ্চয়তা।',
		slogan: 'ক্ষুধা মেটানোর সাধারণ খাবার নয়, এক চরম তৃপ্তির বিস্ফোরণ!',
		whyChooseLabel: 'কেন মুগল দরবার?',
		copyright: `${brandName} রেস্টুরেন্ট। সর্বস্বত্ব সংরক্ষিত।`,
		footerTagline: 'মুগদার সেরা ফাস্ট ফুড ডেস্টিনেশন',
		teamName: brandTeam,
	},
	theme: {
		primary: '#ff9f1c',
		primaryHover: '#f77f00',
		accent: '#ffbf00',
		success: '#25d366',
		successHover: '#22c55e',
		background: '#000000',
		surface: '#0a0a0a',
		surfaceAlt: '#171717',
		borderDefault: 'rgba(255, 255, 255, 0.1)',
		borderSoft: 'rgba(255, 255, 255, 0.05)',
		borderHover: 'rgba(255, 159, 28, 0.5)',
		textSecondary: '#a1a1aa',
	},
	navigation: [
		{ id: 'home', label: 'হোম' },
		{ id: 'menu', label: 'মেনু' },
		{ id: 'blog', label: 'ব্লগ' },
		{ id: 'contact', label: 'যোগাযোগ' },
	],
	contact: {
		primaryPhone,
		secondaryPhone,
		whatsappNumber: '8801917503580',
		addressLines: ['৭৯/৮০, দক্ষিণ মুগদা', 'গার্মেন্টস গলি, দাদা ভিলা এপার্টমেন্ট', 'মুগদা, ঢাকা'],
		hoursLines: ['সকাল ১০টা - রাত ১১টা', 'প্রতিদিন খোলা'],
		mapTitle: `${brandNameLatin} Location`,
		mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3652.0!2d90.4!3d23.75!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjPCsDQ1JzAwLjAiTiA5MMKwMjQnMDAuMCJF!5e0!3m2!1sen!2sbd!4v1234567890',
	},
	whatsapp: {
		href: 'https://wa.me/8801917503580',
		ariaLabel: 'WhatsApp এ মেসেজ করুন',
		orderLabel: 'WhatsApp এ অর্ডার করুন',
		shortOrderLabel: 'WhatsApp এ অর্ডার',
	},
	hero: {
		badge: 'মুগদার সেরা ফাস্ট ফুড',
		headlineTop: 'ক্ষুধা মেটানোর সাধারণ খাবার নয়,',
		headlineBottom: 'এক চরম তৃপ্তির বিস্ফোরণ!',
		subheadlinePrefix: 'সারাদিনের ক্লান্তি শেষে এক কামড়েই মন ভালো করার গ্যারান্টি। মুগদার বুকে আপনার প্রিয় ',
		subheadlineBrand: brandName,
		subheadlineSuffix: ' দিচ্ছে গরম, রসালো এবং জিভে জল আনা স্বাদের প্রতিশ্রুতি।',
		menuCta: 'মেনু দেখুন',
		orderCta: 'গরম গরম অর্ডার করুন',
	},
	home: {
		featuredSectionLabel: 'আমাদের স্পেশাল',
		featuredSectionTitle: 'জিভে জল আনা আইটেম',
		featuredItems,
		whyChooseSectionLabel: brandTeam,
		whyChooseSectionTitle: 'আমাদের বিশেষত্ব',
		features: [
			{
				icon: '🔥',
				title: 'গরম ও তাজা',
				description: 'প্রতিটি অর্ডার তাজা উপকরণ দিয়ে তৈরি এবং গরম গরম পরিবেশন করা হয়',
			},
			{
				icon: '⚡',
				title: 'দ্রুত ডেলিভারি',
				description: 'মুগদা এলাকায় সবচেয়ে দ্রুত ডেলিভারি সার্ভিস',
			},
			{
				icon: '💯',
				title: 'মানের নিশ্চয়তা',
				description: 'সেরা মানের উপকরণ এবং হাইজিনিক পরিবেশে তৈরি',
			},
		],
		ctaTitle: 'ক্ষুধা লাগছে? আর দেরি কেন!',
		ctaText: 'এখনই অর্ডার করুন এবং মুগদার সেরা স্বাদ উপভোগ করুন',
		ctaButton: 'এখনই অর্ডার করুন',
		menuButton: 'মেনু দেখুন',
		orderButton: 'অর্ডার করুন',
		viewAllButton: 'সম্পূর্ণ মেনু দেখুন',
	},
	menu: {
		headerLabel: 'সুস্বাদু খাবার',
		title: 'আমাদের মেনু',
		subtitle: 'মুগদার সেরা স্বাদ - প্রতিটি আইটেম তাজা উপকরণ দিয়ে ভালোবাসা সহকারে তৈরি',
		categories: [
			{ id: 'all', label: 'সব আইটেম' },
			{ id: 'pizza', label: 'পিৎজা' },
			{ id: 'pasta', label: 'চাউমিন/পাস্তা' },
			{ id: 'setmenu', label: 'সেট মেনু' },
		],
		items: menuItems,
		popularLabel: 'জনপ্রিয়',
		orderButton: 'অর্ডার',
		specialNotePrefix: '📞 অর্ডার করতে কল করুন:',
		priceNote: '* দাম পরিবর্তনশীল। সাইজ অনুযায়ী দাম ভিন্ন হতে পারে।',
	},
	blog: {
		headerLabel: 'আমাদের ব্লগ',
		title: 'খাবার নিয়ে গল্প',
		subtitle: 'খাবার শুধু খাওয়া নয়, এর পেছনে আছে বিজ্ঞান, সংস্কৃতি এবং অনেক মজার তথ্য',
		posts: blogPosts,
		newsletterTitle: 'নতুন আপডেট পেতে চান?',
		newsletterText: 'আমাদের নতুন অফার, মেনু আপডেট এবং খাবার নিয়ে মজার তথ্য সবার আগে পেতে সাবস্ক্রাইব করুন',
		newsletterPlaceholder: 'আপনার ইমেইল লিখুন',
		newsletterButton: 'সাবস্ক্রাইব',
	},
	contact: {
		headerLabel: 'যোগাযোগ করুন',
		title: 'অর্ডার',
		titleAccent: 'করুন',
		subtitle: 'গরম গরম সুস্বাদু খাবার এখনই অর্ডার করুন। দ্রুত ডেলিভারি নিশ্চিত।',
		infoTitle: 'যোগাযোগের তথ্য',
		orderFormTitle: 'অর্ডার ফর্ম',
		orderFormSubtitle: 'নিচের ফর্ম পূরণ করে অর্ডার করুন',
		whatsappCta: 'WhatsApp এ অর্ডার করুন',
		formLabels: {
			name: 'আপনার নাম',
			phone: 'ফোন নম্বর',
			address: 'ডেলিভারি ঠিকানা',
			item: 'অর্ডার আইটেম',
		},
		formPlaceholders: {
			name: 'নাম লিখুন',
			phone: '01XXXXXXXXX',
			address: 'সম্পূর্ণ ঠিকানা লিখুন',
			item: 'যেমন: চিকেন পিৎজা ২টি, চিকেন পাস্তা ১টি',
		},
		infoCards: [
			{
				title: 'ঠিকানা',
				details: ['৭৯/৮০, দক্ষিণ মুগদা', 'গার্মেন্টস গলি, দাদা ভিলা এপার্টমেন্ট', 'মুগদা, ঢাকা'],
			},
			{
				title: 'ফোন নম্বর',
				details: [primaryPhone.display, secondaryPhone.display],
				links: [primaryPhone.href, secondaryPhone.href],
			},
			{
				title: 'খোলা থাকে',
				details: ['সকাল ১০:০০ - রাত ১১:০০', 'প্রতিদিন খোলা'],
			},
		],
		mapTitle: `${brandNameLatin} Location`,
		successMessage: 'অসাধারণ সিদ্ধান্ত! আপনার গরম ও সুস্বাদু খাবার তৈরি হচ্ছে।',
		validationMessage: 'অনুগ্রহ করে সব ফিল্ড পূরণ করুন',
		errorMessage: 'অর্ডার সাবমিট করতে সমস্যা হয়েছে',
		processingText: 'প্রসেসিং...',
		confirmText: 'অর্ডার কনফার্ম করুন',
		redirectDelayMs: 2000,
		submitNote: 'অর্ডার কনফার্ম করলে আমরা শীঘ্রই আপনাকে কল করব',
	},
	admin: {
		brandTitle: brandName,
		panelLabel: 'অ্যাডমিন প্যানেল',
		loginPasswordRequired: 'পাসওয়ার্ড দিন',
		loginTitle: brandName,
		loginSubtitle: 'অ্যাডমিন প্যানেল',
		passwordLabel: 'পাসওয়ার্ড',
		passwordPlaceholder: 'পাসওয়ার্ড লিখুন',
		loginButton: 'লগইন করুন',
		loginLoading: 'লগইন হচ্ছে...',
		backToWebsite: '← ওয়েবসাইটে ফিরে যান',
		dashboardBrandLabel: brandName,
		dashboardSubtitle: 'অ্যাডমিন প্যানেল',
		ordersTabLabel: 'অর্ডার',
		menuTabLabel: 'মেনু',
		ordersHeader: 'অর্ডার লিস্ট',
		menuHeader: 'মেনু ম্যানেজমেন্ট',
		addItemButton: 'নতুন আইটেম',
		addItemMobileButton: 'যোগ করুন',
		logoutButton: 'লগআউট',
		loadingText: 'লোড হচ্ছে...',
		emptyOrdersText: 'কোনো অর্ডার নেই',
		emptyMenuText: 'কোনো মেনু আইটেম নেই',
		orderDeleteConfirm: 'এই অর্ডার ডিলিট করতে চান?',
		menuDeleteConfirm: 'এই আইটেম ডিলিট করতে চান?',
		orderDeleteSuccess: 'অর্ডার ডিলিট হয়েছে',
		menuDeleteSuccess: 'আইটেম ডিলিট হয়েছে',
		orderDeleteFailure: 'অর্ডার ডিলিট ব্যর্থ',
		menuDeleteFailure: 'ডিলিট ব্যর্থ হয়েছে',
		statusUpdated: 'স্ট্যাটাস আপডেট হয়েছে',
		statusUpdateFailed: 'স্ট্যাটাস আপডেট ব্যর্থ',
		logoutSuccess: 'লগআউট সফল',
		orderListTitle: 'অর্ডার লিস্ট',
		menuManagementTitle: 'মেনু ম্যানেজমেন্ট',
		orderActions: {
			confirm: 'কনফার্ম',
			cancel: 'বাতিল',
			preparing: 'তৈরি শুরু',
			delivered: 'ডেলিভার্ড',
			delete: 'ডিলিট',
		},
		statusLabels: {
			pending: 'পেন্ডিং',
			confirmed: 'কনফার্মড',
			preparing: 'তৈরি হচ্ছে',
			delivered: 'ডেলিভার্ড',
			cancelled: 'বাতিল',
		},
		menuModal: {
			addTitle: 'নতুন আইটেম যোগ করুন',
			editTitle: 'আইটেম এডিট করুন',
			nameLabel: 'নাম *',
			categoryLabel: 'ক্যাটেগরি',
			priceLabel: 'দাম *',
			sizeLabel: 'সাইজ',
			descriptionLabel: 'বর্ণনা',
			imageLabel: 'ছবির URL',
			popularLabel: 'জনপ্রিয় আইটেম',
			categoryOptions: {
				pizza: 'পিৎজা',
				pasta: 'চাউমিন/পাস্তা',
				setmenu: 'সেট মেনু',
			},
			namePlaceholder: 'চিকেন পিৎজা',
			pricePlaceholder: '১৫০',
			sizePlaceholder: '৭" - ৯"',
			descriptionPlaceholder: 'রসালো চিকেন, চিজ...',
			imagePlaceholder: 'https://...',
			submitNew: 'যোগ করুন',
			submitEdit: 'আপডেট করুন',
			submitting: 'সেভ হচ্ছে...',
			validationError: 'নাম এবং দাম দিন',
			successNew: 'নতুন আইটেম যোগ হয়েছে',
			successEdit: 'আইটেম আপডেট হয়েছে',
			error: 'সমস্যা হয়েছে',
		},
	},
};
